### ISSUE TITLE
Add a README file

### ISSUE THREAD

**Issue by LuayAlali** [LuayAlali/Web-App-Dashboard#1]
Create README file to give an overview of what this repository is for.

**Comment by LuayAlali** [comment]
## TODO

*Description of project*
- [x] How to use it
- [ ]  does it need to be downloaded
- [ ] method behind project creation, languages used,  design, optimization etc

:tada: 🙆🏾‍♂️  🎊 

cc @LuayAlali
